<?xml version="1.0" encoding="utf-8"?>
<!-- Original idea and original stylesheet: https://lepture.com/en/2019/rss-style-with-xsl-->
<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/"
                xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd">
  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
  <xsl:template match="/">
    <html xmlns="http://www.w3.org/1999/xhtml">
      <head>
        <title><xsl:value-of select="/rss/channel/title"/> Feed</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
		<meta charset="UTF-8"/>
		<meta name="viewport" content="width=device-width, initial-scale=1"/>
		<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css"/>
		<link rel="stylesheet" type="text/css" href="css/stylew3.css" />
      </head>
      <body class="w3-light-grey">
		<div class="w3-content" style="max-width:1400px">
        <!--xsl:if test="/rss/channel/itunes:image">
          <div class="top inner">
            This is a Podcast RSS Feed generated by <a href="https://typlog.com/" target="_blank">Typlog</a>.
            Podcast apps can use the URL in the address bar. Find out
            <a href="https://blog.typlog.com/subscribe-podcast-feed" target="_blank">
              how to subscribe a podcast via feed</a>.
          </div>
        </xsl:if>
        <xsl:if test="/rss/channel/item/dc:creator">
          <div class="top inner">
            This is a RSS Feed generated by <a href="https://typlog.com/" target="_blank">Typlog</a>.
            RSS readers can use the URL in the address bar.
          </div>
        </xsl:if-->
        <!--div class="head inner"-->
          <!--xsl:if test="/rss/channel/image">
            <a class="head_logo">
              <xsl:attribute name="href">
                <xsl:value-of select="/rss/channel/link"/>
              </xsl:attribute>
              <img>
                <xsl:attribute name="src">
                  <xsl:value-of select="/rss/channel/image/url"/>
                </xsl:attribute>
                <xsl:attribute name="title">
                  <xsl:value-of select="/rss/channel/title"/>
                </xsl:attribute>
              </img>
            </a>
          </xsl:if-->
          <header class="w3-container w3-center w3-padding-32">
            <h1><xsl:value-of select="/rss/channel/title"/></h1>
            <p><xsl:value-of select="/rss/channel/description"/></p>
            <a class="head_link" target="_blank">
              <xsl:attribute name="href">
                <xsl:value-of select="/rss/channel/link"/>
              </xsl:attribute>
              Visit Website &#x2192;
            </a>
          </header>
        <!--/div-->
        <!--xsl:if test="/rss/channel/atom:link[@rel='alternate']">
          <div class="links inner">
            <xsl:for-each select="/rss/channel/atom:link[@rel='alternate']">
              <a target="_blank">
                <xsl:attribute name="class">
                  <xsl:value-of select="@icon"/>
                </xsl:attribute>
                <xsl:attribute name="href">
                  <xsl:value-of select="@href"/>
                </xsl:attribute>
                <xsl:value-of select="@title"/>
              </a>
            </xsl:for-each>
          </div>
        </xsl:if-->
		<div class="w3-row">
		<div class="w3-col l12 s12">
        <xsl:for-each select="/rss/channel/item">
			<!-- Blog entry -->
			<div class="w3-card-4 w3-margin w3-white">
				<div class="w3-container">
					<h3>
						<a style="color: inherit;">
							<xsl:attribute name="href">
						      <xsl:value-of select="link"/>
						    </xsl:attribute>
						    <xsl:value-of select="title"/>
						</a></h3>
						<div class="w3-row">
							<div class="w3-col m8 s12">
							</div>
							<div class="w3-col m4"><p style="text-align: right">
								<span class="w3-opacity"><xsl:value-of select="pubDate" /></span>
							</p>
							</div>
						</div>
				</div>

				<div class="w3-container">
					<p><xsl:value-of disable-output-escaping="yes" select="description" /></p>
				</div>
			</div>
			<hr/>

          <!--div class="item inner">
            <div class="item_meta">
              <span><xsl:value-of select="pubDate" /></span>
              <xsl:if test="itunes:duration">
                &#x02022;
                <span><xsl:value-of select="itunes:duration" /></span>
              </xsl:if>
            </div>
            <h2>
              <a target="_blank">
                <xsl:attribute name="href">
                  <xsl:value-of select="link"/>
                </xsl:attribute>
                <xsl:value-of select="title"/>
              </a>
            </h2>
            <xsl:if test="itunes:subtitle">
              <h3><xsl:value-of select="itunes:subtitle" /></h3>
            </xsl:if>
            <xsl:if test="itunes:duration">
              <audio controls="true" preload="none">
                <xsl:attribute name="src">
                  <xsl:value-of select="enclosure/@url"/>
                </xsl:attribute>
              </audio>
            </xsl:if>
          </div-->
        </xsl:for-each>
		</div>
		</div>
        <!--div class="typlog-foot">
          <a class="title" href="https://typlog.com/?utm_medium=feed">Typlog</a>
          <nav>
            <a href="https://typlog.com/about?utm_medium=feed">About</a>
            <a href="https://typlog.com/terms?utm_medium=feed">Terms</a>
          </nav>
        </div-->
		</div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
